/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Mobile mobile = new Mobile("GTS105", "black", "Nokia");

        IPhone iphoneMobile = new IPhone("IPhone 8", "black", "Apple");

        AndroidMobile androidMobile = new AndroidMobile("P30 Pro", "blue", "HUAWEI");

//        System.out.println(mobile.toString());
        Person person = new Person("AKin");
        person.setMobile(iphoneMobile);
        person.getMobile().makeACall("Message cannot be sent");
        person.setMobile(androidMobile);
        person.getMobile().makeACall("Message cannot be sent");

        IPhoneRobot iPhoneRobot = new IPhoneRobot();
        iPhoneRobot.setiPhone(iphoneMobile);
        iPhoneRobot.getiPhone().makeACall("iphoneRobot's message cannot be sent");

//        System.out.println(new App().getGreeting());
    }
}
